### ISSUE TITLE
Project Github Cordialidad

### ISSUE THREAD

**Issue by dmj619** [PRIS2/cordialidad#2]
Hola Buenas Tardes,
En primer lugar he creado un proyecto en GitHub asociado al grupo de cordialidad. Se ha creado por defecto con los tableros predefinidos básicos. ¿Estáis de acuerdo? , ¿Qué otras tableros que se podía crear?

Espero vuestra contestación.
Atentamente, David.
Un saludo.

**Comment by trm187** [comment]
Buenas!
Deberíamos modificar los tableros básicos y adaptarlos a lo que necesitamos.

Un saludo.
Tesi.

**Comment by dogudo** [comment]
Hola a todos!

Me parece buena idea, quizá por el momento pueda valer pero si fuera necesario hará falta adaptarlos.

**Comment by MM-Cosmin** [comment]
Hola chicos!

Yo opino que con los 3 por defecto que viene es suficiente.

**Comment by alcaval** [comment]
Buenas,
en cualquier caso alguna de sugerencias para el proyecto, pero lo veo perfecto.
