### ISSUE TITLE
Subida de capturas

### ISSUE THREAD

**Issue by trm187** [PRIS2/cordialidad#3]
Buenas!
Yo ya he subido la mía, comentad debajo cuando hayáis subido la vuestra.
Un saludo.

**Comment by dmj619** [comment]
Hola Buenas Tardes,
Acabo de subir un par de capturas

Un Saludo!

**Comment by MM-Cosmin** [comment]
Buenas!
Ya he subido la campura.

**Comment by dogudo** [comment]
Hola a todos, ya he subido la captura también 👍

**Comment by alcaval** [comment]
Buenas ya he subido la captura de la reunion por discord
