### ISSUE TITLE
Fin proyecto

### ISSUE THREAD

**Issue by dmj619** [PRIS2/cordialidad#5]
Hola Buenas Tardes, 
Voy a subir ala documentación y el proyecto al repositorio GitHub. Con esto queda concluido esta tarea

Un Saludo.

**Comment by trm187** [comment]
Buenas tardes.
Vamos a arreglar los fallos que sacamos de la clase de dudas del otro dia.

**Comment by dmj619** [comment]
Lo arreglamos ahora en la sesión 03 de trabajo

**Comment by alcaval** [comment]
Ya esta fixeado, post reunion, se cierra el issue
